# Generated by Django 6.0.7 on 2026-09-25 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0044_alter_interpretationrule_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationFormula',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_number', models.PositiveIntegerField(unique=True)),
                ('case_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(help_text='Mathematical formula expression')),
                ('variables', models.JSONField(blank=True, default=list)),
                ('result_unit', models.CharField(default='percentage', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calculation_formulas',
                'ordering': ['case_number'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSectionCalculationRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE', 'State Board'), ('IB', 'IB'), ('IGCSE', 'IGCSE'), ('ALL', 'All Boards')], default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_calculation_rules', to='assessments.assessmentversion')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_calculation_rules', to='assessments.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_rules', to='assessments.section')),
                ('calculation_formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_rules', to='calculate.calculationformula')),
            ],
            options={
                'db_table': 'assessment_section_calculation_rules',
                'indexes': [models.Index(fields=['assessment_version', 'section'], name='assessment__assessm_44fd47_idx'), models.Index(fields=['grade', 'board'], name='assessment__grade_i_791407_idx'), models.Index(fields=['calculation_formula'], name='assessment__calcula_254cf4_idx'), models.Index(fields=['status'], name='assessment__status_c62017_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('grade__isnull', False)), fields=('assessment_version', 'section', 'grade', 'board'), name='unique_section_formula_grade_board'), models.UniqueConstraint(condition=models.Q(('grade__isnull', True)), fields=('assessment_version', 'section', 'board'), name='unique_section_formula_all_grades_board')],
            },
        ),
    ]
