# Generated by Django 6.0.7 on 2026-07-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('student_code', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_photo', models.URLField(blank=True, help_text='S3/CDN Profile Photo URL', null=True)),
                ('parent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('parent_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=30, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('class_name', models.CharField(blank=True, max_length=30, null=True)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ASSESSMENT_ASSIGNED', 'Assessment Assigned'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('REPORT_GENERATED', 'Report Generated'), ('COUNSELLING_PENDING', 'Counselling Pending'), ('COUNSELLING_COMPLETED', 'Counselling Completed')], default='REGISTERED', max_length=30)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_counsellor', to='accounts.organizationmember')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='organizations.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='organizations.organization')),
                ('registration_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registrations_channel', to='organizations.registrationchannel')),
                ('registration_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='organizations.registrationlink')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Registration',
                'verbose_name_plural': 'Student Registrations',
                'db_table': 'student_registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['public_id'], name='students_public__ecf8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_code'], name='students_student_cdda5e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_status_3ac771_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['public_id'], name='student_reg_public__7976d2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['student'], name='student_reg_student_b6f20c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['organization'], name='student_reg_organiz_66c871_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['campaign'], name='student_reg_campaig_3ad844_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['registration_channel'], name='student_reg_registr_1796df_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['registration_link'], name='student_reg_registr_826be0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['registration_number'], name='student_reg_registr_35baed_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['registration_status'], name='student_reg_registr_4a5b35_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['academic_year'], name='student_reg_academi_a8dcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['registered_at'], name='student_reg_registe_129cf7_idx'),
        ),
    ]
