# Generated by Django 6.0.7 on 2026-09-18 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organizationmember_alter_registrationlink_options_and_more'),
        ('students', '0002_alter_student_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='assigned_counsellor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_counsellor', to='organizations.organizationmember'),
        ),
    ]
