# Generated by Django 6.0.7 on 2026-09-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0044_alter_interpretationrule_title'),
        ('organizations', '0011_alter_organizationpackage_currency_and_more'),
        ('students', '0003_alter_studentregistration_assigned_counsellor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentregistration',
            name='student_reg_campaig_3ad844_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentregistration',
            name='student_reg_registr_1796df_idx',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='registration_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registrations', to='assessments.grade'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='registration_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='organizations.registrationlink'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='registration_status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('ASSESSMENT_ASSIGNED', 'Assessment Assigned'), ('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_SHARED', 'Report Shared'), ('COUNSELLING_PENDING', 'Counselling Pending'), ('COUNSELLING_COMPLETED', 'Counselling Completed')], default='REGISTERED', max_length=30),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['registration_type'], name='student_reg_registr_e5f575_idx'),
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='registration_channel',
        ),
    ]
