# Generated by Django 6.0.7 on 2026-09-23 09:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_organizationpackage_currency_and_more'),
        ('students', '0004_remove_studentregistration_student_reg_campaig_3ad844_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='organizations.package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='students.student')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_id'], name='orders_public__b44ebc_idx'), models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'), models.Index(fields=['student'], name='orders_student_4f4f01_idx'), models.Index(fields=['package'], name='orders_package_2b71b9_idx'), models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['created_at'], name='orders_created_77e2b9_idx')],
            },
        ),
    ]
