# Generated by Django 6.0.7 on 2026-07-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentversion',
            name='report_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_versions', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='assessmentgrademapping',
            name='assessment_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_mappings', to='assessments.assessmentversion'),
        ),
        migrations.AddField(
            model_name='assessmentdimensionweight',
            name='assessment_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_weights', to='assessments.assessmentversion'),
        ),
        migrations.AddField(
            model_name='assessmentblueprintitem',
            name='assessment_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_items', to='assessments.assessmentversion'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['dimension_code'], name='dimensions_dimensi_a3af6d_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['name'], name='dimensions_name_76faca_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['status'], name='dimensions_status_7b5d41_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['display_order'], name='dimensions_display_4f9e12_idx'),
        ),
        migrations.AddField(
            model_name='assessmentdimensionweight',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_weights', to='assessments.dimension'),
        ),
        migrations.AddField(
            model_name='interpretationrule',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_rules', to='assessments.dimension'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentblueprintitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_items', to='assessments.question'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['public_id'], name='question_ca_public__564182_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['category_code'], name='question_ca_categor_ed8935_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['name'], name='question_ca_name_5a8210_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['status'], name='question_ca_status_632a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['display_order'], name='question_ca_display_f1c6c5_idx'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessments.questioncategory'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='recommendationrule',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_rules', to='assessments.dimension'),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='assessments.dimension'),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='assessments.questionoption'),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='section',
            name='assessment_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.assessmentversion'),
        ),
        migrations.AddField(
            model_name='assessmentblueprintitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_items', to='assessments.section'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsections', to='assessments.dimension'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='assessments.section'),
        ),
        migrations.AddField(
            model_name='assessmentblueprintitem',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_items', to='assessments.subsection'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['public_id'], name='assessments_public__5c33f5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_code'], name='assessments_assessm_b01ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['name'], name='assessments_name_11eba9_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_type'], name='assessments_assessm_603d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status'], name='assessments_status_621393_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentversion',
            index=models.Index(fields=['public_id'], name='assessment__public__759e45_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentversion',
            index=models.Index(fields=['assessment'], name='assessment__assessm_9815e3_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentversion',
            index=models.Index(fields=['version_number'], name='assessment__version_5acbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentversion',
            index=models.Index(fields=['status'], name='assessment__status_fbcd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentversion',
            index=models.Index(fields=['effective_from'], name='assessment__effecti_c8c06c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentversion',
            index=models.Index(fields=['effective_to'], name='assessment__effecti_a0833b_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.UniqueConstraint(fields=('assessment', 'version_number'), name='unique_assessment_version'),
        ),
        migrations.AddIndex(
            model_name='assessmentgrademapping',
            index=models.Index(fields=['public_id'], name='assessment__public__220d75_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentgrademapping',
            index=models.Index(fields=['assessment_version'], name='assessment__assessm_bcfe3d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentgrademapping',
            index=models.Index(fields=['grade'], name='assessment__grade_d68f16_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentgrademapping',
            index=models.Index(fields=['board'], name='assessment__board_b72714_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentgrademapping',
            index=models.Index(fields=['status'], name='assessment__status_3e6ddd_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentgrademapping',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'grade', 'board'), name='unique_assessment_grade_board'),
        ),
        migrations.AddIndex(
            model_name='assessmentdimensionweight',
            index=models.Index(fields=['public_id'], name='assessment__public__4f802d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentdimensionweight',
            index=models.Index(fields=['assessment_version'], name='assessment__assessm_05b717_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentdimensionweight',
            index=models.Index(fields=['dimension'], name='assessment__dimensi_56d71d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentdimensionweight',
            index=models.Index(fields=['display_order'], name='assessment__display_087f75_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdimensionweight',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'dimension'), name='unique_dimension_per_assessment_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdimensionweight',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'display_order'), name='unique_dimension_display_order'),
        ),
        migrations.AddIndex(
            model_name='interpretationrule',
            index=models.Index(fields=['public_id'], name='interpretat_public__f3b96d_idx'),
        ),
        migrations.AddIndex(
            model_name='interpretationrule',
            index=models.Index(fields=['dimension'], name='interpretat_dimensi_20f031_idx'),
        ),
        migrations.AddIndex(
            model_name='interpretationrule',
            index=models.Index(fields=['min_score'], name='interpretat_min_sco_4ece9d_idx'),
        ),
        migrations.AddIndex(
            model_name='interpretationrule',
            index=models.Index(fields=['max_score'], name='interpretat_max_sco_fe3d38_idx'),
        ),
        migrations.AddIndex(
            model_name='interpretationrule',
            index=models.Index(fields=['display_color'], name='interpretat_display_70e189_idx'),
        ),
        migrations.AddConstraint(
            model_name='interpretationrule',
            constraint=models.UniqueConstraint(fields=('dimension', 'display_color'), name='unique_interpretation_order_per_dimension'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['uuid'], name='questions_uuid_8edc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_code'], name='questions_questio_72cf05_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='questions_categor_88b3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='questions_questio_8af709_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty_level'], name='questions_difficu_3585ab_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['language'], name='questions_languag_ccb86f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='questions_is_acti_ba6b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['public_id'], name='question_op_public__2036fa_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question'], name='question_op_questio_dc3834_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['option_code'], name='question_op_option__e55632_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['display_order'], name='question_op_display_0b6696_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['status'], name='question_op_status_56128f_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_code'), name='unique_option_code_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'display_order'), name='unique_option_order_per_question'),
        ),
        migrations.AddIndex(
            model_name='recommendationrule',
            index=models.Index(fields=['public_id'], name='recommendat_public__891239_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrule',
            index=models.Index(fields=['dimension'], name='recommendat_dimensi_e1c8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrule',
            index=models.Index(fields=['rating'], name='recommendat_rating_1c028e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrule',
            index=models.Index(fields=['priority'], name='recommendat_priorit_dc43ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationrule',
            constraint=models.UniqueConstraint(fields=('dimension', 'rating', 'priority'), name='unique_recommendation_per_rating'),
        ),
        migrations.AddIndex(
            model_name='scoringrule',
            index=models.Index(fields=['question'], name='scoring_rul_questio_448a98_idx'),
        ),
        migrations.AddIndex(
            model_name='scoringrule',
            index=models.Index(fields=['option'], name='scoring_rul_option__ef4b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='scoringrule',
            index=models.Index(fields=['dimension'], name='scoring_rul_dimensi_9e46e0_idx'),
        ),
        migrations.AddIndex(
            model_name='scoringrule',
            index=models.Index(fields=['is_correct'], name='scoring_rul_is_corr_4a87b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoringrule',
            constraint=models.UniqueConstraint(fields=('question', 'option', 'dimension'), name='unique_question_option_dimension_score'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['public_id'], name='sections_public__4ab91e_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['assessment_version'], name='sections_assessm_6611ed_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_code'], name='sections_section_a5a5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['status'], name='sections_status_1b1ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['display_order'], name='sections_display_67d87c_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'section_code'), name='unique_section_code_per_version'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['public_id'], name='subsections_public__93d962_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['section'], name='subsections_section_5a72bd_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['dimension'], name='subsections_dimensi_347de3_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['subsection_code'], name='subsections_subsect_afe3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['status'], name='subsections_status_0aaa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['display_order'], name='subsections_display_b71947_idx'),
        ),
        migrations.AddConstraint(
            model_name='subsection',
            constraint=models.UniqueConstraint(fields=('section', 'subsection_code'), name='unique_subsection_code_per_section'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprintitem',
            index=models.Index(fields=['assessment_version'], name='assessment__assessm_31abed_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprintitem',
            index=models.Index(fields=['section'], name='assessment__section_e67c59_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprintitem',
            index=models.Index(fields=['subsection'], name='assessment__subsect_ab9b93_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprintitem',
            index=models.Index(fields=['question'], name='assessment__questio_bb8027_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprintitem',
            index=models.Index(fields=['sequence_no'], name='assessment__sequenc_cae228_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprintitem',
            index=models.Index(fields=['status'], name='assessment__status_b7c5d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentblueprintitem',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'question'), name='unique_question_per_assessment_version'),
        ),
    ]
