# Generated by Django 6.0.7 on 2026-07-27 06:32

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessment_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='questions_uuid_8edc8d_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['public_id'], name='questions_public__984799_idx'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='uuid',
        ),
    ]
