# Generated by Django 6.0.7 on 2026-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_assessment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='icon',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
