# Generated by Django 6.0.7 on 2026-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_assessment_icon_alter_assessment_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('CAREER', 'Career'), ('APTITUDE', 'Aptitude'), ('INTEREST', 'Interest'), ('PERSONALITY', 'Personality'), ('PSYCHOMETRIC', 'Psychometric'), ('LEARNING_STYLE', 'Learning_style'), ('CUSTOM', 'Custom')], max_length=20),
        ),
    ]
