# Generated by Django 6.0.7 on 2026-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_assessment_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='icon',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='assessment/icons/'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='assessment/thumbnails/'),
        ),
    ]
