# Generated by Django 6.0.7 on 2026-07-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_alter_assessment_icon_alter_assessment_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentgrademapping',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
