# Generated by Django 6.0.7 on 2026-07-29 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_assessmentgrademapping_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('grade_code', models.CharField(help_text='Example: GRADE_10', max_length=20, unique=True)),
                ('grade_name', models.CharField(help_text='Example: Grade 10', max_length=50, unique=True)),
                ('education_level', models.CharField(choices=[('SCHOOL', 'School'), ('UG', 'Under Graduate'), ('PG', 'Post Graduate')], default='SCHOOL', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Used for UI sorting')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['display_order', 'grade_name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGradeMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Grade Mapping',
                'verbose_name_plural': 'Question Grade Mappings',
                'db_table': 'question_grade_mappings',
                'ordering': ['grade', 'question'],
            },
        ),
        migrations.RemoveIndex(
            model_name='questioncategory',
            name='question_ca_public__564182_idx',
        ),
        migrations.RemoveIndex(
            model_name='questioncategory',
            name='question_ca_categor_ed8935_idx',
        ),
        migrations.RemoveIndex(
            model_name='questioncategory',
            name='question_ca_name_5a8210_idx',
        ),
        migrations.RemoveIndex(
            model_name='questioncategory',
            name='question_ca_status_632a5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='questioncategory',
            name='question_ca_display_f1c6c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_categor_88b3fe_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentgrademapping',
            new_name='assessment__grade_i_8d55e3_idx',
            old_name='assessment__grade_d68f16_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessments.subsection'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subsection'], name='questions_subsect_01d589_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['public_id'], name='grades_public__f5191f_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['grade_code'], name='grades_grade_c_d009c8_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['grade_name'], name='grades_grade_n_24cf13_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['education_level'], name='grades_educati_b5ba9c_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['status'], name='grades_status_841560_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['display_order'], name='grades_display_ebeb91_idx'),
        ),
        migrations.AlterField(
            model_name='assessmentgrademapping',
            name='grade',
            field=models.ForeignKey(help_text='Applicable Grade (e.g. 8, 9, 10, 11, 12)', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_grade_mappings', to='assessments.grade'),
        ),
        migrations.AddField(
            model_name='questiongrademapping',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='assessments.grade'),
        ),
        migrations.AddField(
            model_name='questiongrademapping',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_mappings', to='assessments.question'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddIndex(
            model_name='questiongrademapping',
            index=models.Index(fields=['public_id'], name='question_gr_public__79cbef_idx'),
        ),
        migrations.AddIndex(
            model_name='questiongrademapping',
            index=models.Index(fields=['question'], name='question_gr_questio_c0d52f_idx'),
        ),
        migrations.AddIndex(
            model_name='questiongrademapping',
            index=models.Index(fields=['grade'], name='question_gr_grade_i_867f6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiongrademapping',
            constraint=models.UniqueConstraint(fields=('question', 'grade'), name='unique_question_grade_mapping'),
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
    ]
