# Generated by Django 6.0.7 on 2026-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_grade_questiongrademapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='time_limit_minutes',
        ),
        migrations.AddField(
            model_name='subsection',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
