# Generated by Django 6.0.7 on 2026-07-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_remove_section_time_limit_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentversion',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='section',
            name='assessment_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.assessmentversion'),
        ),
    ]
