# Generated by Django 6.0.7 on 2026-07-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_alter_assessmentversion_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20),
        ),
    ]
