# Generated by Django 6.0.7 on 2026-07-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_alter_assessment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
