# Generated by Django 6.0.7 on 2026-08-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_alter_assessment_assessment_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_section_code_per_version',
        ),
        migrations.RemoveConstraint(
            model_name='subsection',
            name='unique_subsection_code_per_section',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='sections_assessm_6611ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='subsection',
            name='subsections_section_5a72bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='subsection',
            name='subsections_dimensi_347de3_idx',
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('section_code',), name='unique_section_code_per_version'),
        ),
        migrations.AddConstraint(
            model_name='subsection',
            constraint=models.UniqueConstraint(fields=('subsection_code',), name='unique_subsection_code_per_section'),
        ),
        migrations.RemoveField(
            model_name='section',
            name='assessment_version',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='section',
        ),
    ]
