# Generated by Django 6.0.7 on 2026-08-01 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_remove_section_unique_section_code_per_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentblueprintitem',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_items', to='assessments.question'),
        ),
    ]
