# Generated by Django 6.0.7 on 2026-08-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_alter_assessmentblueprintitem_question'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subsection',
            name='unique_subsection_code_per_section',
        ),
    ]
