# Generated by Django 6.0.7 on 2026-08-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0019_remove_subsection_unique_subsection_code_per_section'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assessmentdimensionweight',
            name='assessment__public__4f802d_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentdimensionweight',
            name='assessment__assessm_05b717_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentdimensionweight',
            name='assessment__dimensi_56d71d_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentdimensionweight',
            name='assessment__display_087f75_idx',
        ),
        migrations.RemoveConstraint(
            model_name='assessmentdimensionweight',
            name='unique_dimension_per_assessment_version',
        ),
        migrations.RemoveConstraint(
            model_name='assessmentdimensionweight',
            name='unique_dimension_display_order',
        ),
        migrations.AlterModelOptions(
            name='interpretationrule',
            options={'ordering': ['display_color'], 'verbose_name': 'Interpretation Rule', 'verbose_name_plural': 'Interpretation Rules'},
        ),
        migrations.AlterModelOptions(
            name='recommendationrule',
            options={'ordering': ['priority'], 'verbose_name': 'Recommendation Rule', 'verbose_name_plural': 'Recommendation Rules'},
        ),
        migrations.RemoveConstraint(
            model_name='interpretationrule',
            name='unique_interpretation_order_per_dimension',
        ),
        migrations.RemoveConstraint(
            model_name='recommendationrule',
            name='unique_recommendation_per_rating',
        ),
        migrations.RemoveConstraint(
            model_name='scoringrule',
            name='unique_question_option_dimension_score',
        ),
        migrations.RemoveIndex(
            model_name='interpretationrule',
            name='interpretat_dimensi_20f031_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendationrule',
            name='recommendat_dimensi_e1c8c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='scoringrule',
            name='scoring_rul_dimensi_9e46e0_idx',
        ),
        migrations.RenameField(
            model_name='interpretationrule',
            old_name='interpretation',
            new_name='action_plan',
        ),
        migrations.AddField(
            model_name='interpretationrule',
            name='assessment_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_rules', to='assessments.assessmentversion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interpretationrule',
            name='performance_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpretationrule',
            name='subsection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_rules', to='assessments.subsection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendationrule',
            name='assessment_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_rules', to='assessments.assessmentversion'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='interpretationrule',
            index=models.Index(fields=['assessment_version'], name='interpretat_assessm_977b09_idx'),
        ),
        migrations.AddIndex(
            model_name='interpretationrule',
            index=models.Index(fields=['subsection'], name='interpretat_subsect_ddf7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrule',
            index=models.Index(fields=['assessment_version'], name='recommendat_assessm_f6803e_idx'),
        ),
        migrations.AddConstraint(
            model_name='interpretationrule',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'subsection', 'display_color'), name='unique_interpretation_order_per_subsection'),
        ),
        migrations.AddConstraint(
            model_name='recommendationrule',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'rating', 'priority'), name='unique_recommendation_per_rating'),
        ),
        migrations.AddConstraint(
            model_name='scoringrule',
            constraint=models.UniqueConstraint(fields=('question', 'option'), name='unique_question_option_score'),
        ),
        migrations.RemoveField(
            model_name='interpretationrule',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='recommendationrule',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='dimension',
        ),
        migrations.DeleteModel(
            name='AssessmentDimensionWeight',
        ),
    ]
