# Generated by Django 6.0.7 on 2026-08-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_remove_assessmentdimensionweight_assessment__public__4f802d_idx_and_more'),
        ('evaluation', '0004_remove_dimensionresult_dimension_r_evaluat_d9f624_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assessmentgrademapping',
            name='assessment__public__220d75_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentgrademapping',
            name='assessment__assessm_bcfe3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentgrademapping',
            name='assessment__grade_i_8d55e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentgrademapping',
            name='assessment__board_b72714_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentgrademapping',
            name='assessment__status_3e6ddd_idx',
        ),
        migrations.RemoveConstraint(
            model_name='assessmentgrademapping',
            name='unique_assessment_grade_board',
        ),
        migrations.RemoveIndex(
            model_name='dimension',
            name='dimensions_dimensi_a3af6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimension',
            name='dimensions_name_76faca_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimension',
            name='dimensions_status_7b5d41_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimension',
            name='dimensions_display_4f9e12_idx',
        ),
        migrations.DeleteModel(
            name='Dimension',
        ),
        migrations.RemoveField(
            model_name='assessmentversion',
            name='minimum_qualifying_marks',
        ),
        migrations.RemoveField(
            model_name='assessmentversion',
            name='minimum_qualifying_percentage',
        ),
        migrations.RemoveField(
            model_name='assessmentversion',
            name='randomize_questions',
        ),
        migrations.RemoveField(
            model_name='section',
            name='randomize_questions',
        ),
        migrations.AddField(
            model_name='assessmentblueprintitem',
            name='board',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE', 'State Board'), ('IB', 'IB'), ('IGCSE', 'IGCSE'), ('ALL', 'All Boards')], default='ALL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessmentblueprintitem',
            name='grade',
            field=models.ForeignKey(default=1, help_text='Applicable Grade (e.g. 8, 9, 10, 11, 12)', on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_items', to='assessments.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsection',
            name='randomize_questions',
            field=models.BooleanField(blank=True, default=False, help_text='Randomize the order of questions in this subsection', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentblueprintitem',
            name='is_mandatory',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentblueprintitem',
            name='is_randomizable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentblueprintitem',
            name='is_visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentblueprintitem',
            name='sequence_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='allow_resume',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='allow_review',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='randomize_sections',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='total_questions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='total_sections',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='total_subsections',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_mandatory',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.DeleteModel(
            name='AssessmentGradeMapping',
        ),
    ]
