# Generated by Django 6.0.7 on 2026-08-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_remove_assessmentgrademapping_assessment__public__220d75_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Used for UI sorting', null=True),
        ),
    ]
