# Generated by Django 6.0.7 on 2026-08-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0022_alter_grade_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Used for UI sorting', null=True),
        ),
    ]
