# Generated by Django 6.0.7 on 2026-08-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_alter_section_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='education_level',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('HIGHER_SECONDARY', 'Higher Secondary'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='SCHOOL', max_length=20),
        ),
    ]
