# Generated by Django 6.0.7 on 2026-08-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0024_alter_grade_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
