# Generated by Django 6.0.7 on 2026-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0025_question_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
