# Generated by Django 6.0.7 on 2026-08-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_question_media_file_alter_question_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentblueprintitem',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='assessmentblueprintitem',
            name='is_randomizable',
        ),
        migrations.RemoveField(
            model_name='assessmentblueprintitem',
            name='is_visible',
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
