# Generated by Django 6.0.7 on 2026-08-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_remove_assessmentblueprintitem_is_mandatory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentblueprintitem',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Applicable Grade (e.g. 8, 9, 10, 11, 12)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_items', to='assessments.grade'),
        ),
        migrations.AlterField(
            model_name='assessmentblueprintitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_items', to='assessments.section'),
        ),
        migrations.AlterField(
            model_name='assessmentblueprintitem',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_items', to='assessments.subsection'),
        ),
    ]
