# Generated by Django 6.0.7 on 2026-08-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_alter_assessmentblueprintitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentblueprintitem',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20),
        ),
    ]
