# Generated by Django 6.0.7 on 2026-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0030_alter_assessmentblueprintitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, help_text='Used for Aptitude / Knowledge based assessments.', null=True),
        ),
    ]
