# Generated by Django 6.0.7 on 2026-08-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0031_alter_questionoption_is_correct'),
        ('reports', '0003_alter_reporttemplate_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentversion',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_versions', to='reports.reporttemplate'),
        ),
    ]
