# Generated by Django 6.0.7 on 2026-08-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0032_alter_assessmentversion_report_template'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='questions_subsect_01d589_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subsection',
        ),
    ]
