# Generated by Django 6.0.7 on 2026-08-25 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0033_remove_question_questions_subsect_01d589_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tag_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['tag_name'],
                'indexes': [models.Index(fields=['public_id'], name='tags_public__3f2fb0_idx'), models.Index(fields=['tag_name'], name='tags_tag_nam_91d860_idx')],
            },
        ),
        migrations.AddField(
            model_name='questiongrademapping',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_mappings', to='assessments.tags'),
        ),
    ]
