# Generated by Django 6.0.7 on 2026-08-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0034_tags_questiongrademapping_tag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questiongrademapping',
            name='unique_question_grade_mapping',
        ),
        migrations.AddConstraint(
            model_name='questiongrademapping',
            constraint=models.UniqueConstraint(fields=('question', 'grade', 'tag'), name='unique_question_grade_tag_mapping'),
        ),
    ]
