# Generated by Django 6.0.7 on 2026-08-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_remove_questiongrademapping_unique_question_grade_mapping_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questiongrademapping',
            index=models.Index(fields=['tag'], name='question_gr_tag_id_feec3c_idx'),
        ),
    ]
