# Generated by Django 6.0.7 on 2026-08-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0036_questiongrademapping_question_gr_tag_id_feec3c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
