# Generated by Django 6.0.7 on 2026-08-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0037_alter_tags_tag_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmentblueprintitem',
            name='unique_question_per_assessment_version',
        ),
    ]
