# Generated by Django 6.0.7 on 2026-09-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0038_remove_assessmentblueprintitem_unique_question_per_assessment_version'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assessmentblueprintitem',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('assessment_version', 'grade', 'board', 'section', 'subsection', 'question'), name='unique_blueprint_question'),
        ),
        migrations.AddConstraint(
            model_name='assessmentblueprintitem',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', True)), fields=('assessment_version', 'grade', 'board', 'section', 'subsection'), name='unique_blueprint_subsection'),
        ),
    ]
