# Generated by Django 6.0.7 on 2026-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0039_assessmentblueprintitem_unique_blueprint_question_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assessmentblueprintitem',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', True), ('section__isnull', True), ('subsection__isnull', True)), fields=('assessment_version', 'grade', 'board'), name='unique_blueprint_grade_only'),
        ),
    ]
