# Generated by Django 6.0.7 on 2026-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0040_assessmentblueprintitem_unique_blueprint_grade_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='media_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
