# Generated by Django 6.0.7 on 2026-09-05 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0041_alter_question_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationrule',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
