# Generated by Django 6.0.7 on 2026-09-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0042_alter_interpretationrule_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretationrule',
            name='action_plan_option1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpretationrule',
            name='action_plan_option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpretationrule',
            name='action_plan_option3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpretationrule',
            name='action_plan_option4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpretationrule',
            name='action_plan_option5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpretationrule',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20),
        ),
    ]
