# Generated by Django 6.0.7 on 2026-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0043_interpretationrule_action_plan_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationrule',
            name='title',
            field=models.CharField(blank=True, help_text='Example: Outstanding, Strong, Moderate', max_length=100, null=True),
        ),
    ]
