# Generated by Django 6.0.7 on 2026-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0044_alter_interpretationrule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentversion',
            name='section_wise_randomize_question',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
