# Generated by Django 6.0.7 on 2026-09-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0045_assessmentversion_section_wise_randomize_question'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assessmentblueprintitem',
            index=models.Index(fields=['assessment_version', 'grade', 'status'], name='bp_version_grade_status_idx'),
        ),
    ]
