# Generated by Django 6.0.7 on 2026-07-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('organization_code', models.CharField(max_length=20, unique=True)),
                ('organization_type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('COACHING', 'Coaching Institute'), ('COUNSELLOR', 'Independent Counsellor'), ('ENTERPRISE', 'Enterprise'), ('NGO', 'NGO'), ('FRANCHISE', 'Franchise')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['public_id'], name='organizatio_public__9192af_idx'), models.Index(fields=['organization_code'], name='organizatio_organiz_6f5012_idx'), models.Index(fields=['organization_type'], name='organizatio_organiz_650025_idx'), models.Index(fields=['status'], name='organizatio_status_195db0_idx'), models.Index(fields=['city'], name='organizatio_city_3b2795_idx')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('campaign_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='assessments.assessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationChannel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('channel_code', models.CharField(max_length=30, unique=True)),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('CLASS', 'Class'), ('SECTION', 'Section'), ('WEBSITE', 'Website'), ('QR_CODE', 'QR Code'), ('COUNSELLOR', 'Counsellor'), ('SEMINAR', 'Seminar'), ('EXTERNAL_PARTNER', 'External Partner'), ('BULK_IMPORT', 'Bulk Import')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_channels', to='organizations.campaign')),
            ],
            options={
                'verbose_name': 'Registration Channel',
                'verbose_name_plural': 'Registration Channels',
                'db_table': 'registration_channels',
                'ordering': ['display_order', 'channel_name'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('link_code', models.CharField(max_length=100, unique=True)),
                ('registration_channel', models.CharField(choices=[('CLASS_6', 'Class 6'), ('CLASS_7', 'Class 7'), ('CLASS_8', 'Class 8'), ('CLASS_9', 'Class 9'), ('CLASS_10', 'Class 10'), ('CLASS_11', 'Class 11'), ('CLASS_12', 'Class 12'), ('COLLEGE', 'College'), ('WEBSITE', 'Website'), ('QR_CODE', 'QR Code'), ('COUNSELLOR', 'Counsellor'), ('BULK_IMPORT', 'Bulk Import'), ('DIRECT_LINK', 'Direct Link')], max_length=30)),
                ('registration_source', models.CharField(choices=[('URL', 'URL'), ('QR_CODE', 'QR Code'), ('MANUAL', 'Manual'), ('API', 'API'), ('EXCEL_IMPORT', 'Excel Import')], max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('max_registrations', models.PositiveIntegerField(blank=True, null=True)),
                ('registrations_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allow_duplicate_email', models.BooleanField(default=False)),
                ('allow_duplicate_mobile', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentversion')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_links', to='organizations.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Link',
                'verbose_name_plural': 'Registration Links',
                'db_table': 'registration_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['public_id'], name='campaigns_public__3e7817_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization'], name='campaigns_organiz_e9d077_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_code'], name='campaigns_campaig_4cc062_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['assessment'], name='campaigns_assessm_da5b80_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaigns_status_a03570_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='campaigns_start_d_5c2c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['end_date'], name='campaigns_end_dat_6aaba4_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationchannel',
            index=models.Index(fields=['public_id'], name='registratio_public__d8cb78_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationchannel',
            index=models.Index(fields=['campaign'], name='registratio_campaig_eb66c5_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationchannel',
            index=models.Index(fields=['channel_code'], name='registratio_channel_0a70af_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationchannel',
            index=models.Index(fields=['channel_type'], name='registratio_channel_a0ec7e_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationchannel',
            index=models.Index(fields=['status'], name='registratio_status_428561_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationlink',
            index=models.Index(fields=['public_id'], name='registratio_public__af1845_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationlink',
            index=models.Index(fields=['campaign'], name='registratio_campaig_80a58c_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationlink',
            index=models.Index(fields=['link_code'], name='registratio_link_co_2c8477_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationlink',
            index=models.Index(fields=['is_active'], name='registratio_is_acti_9bd6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationlink',
            index=models.Index(fields=['expires_at'], name='registratio_expires_d2eb21_idx'),
        ),
    ]
