# Generated by Django 6.0.7 on 2026-09-11 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0044_alter_interpretationrule_title'),
        ('organizations', '0002_alter_campaign_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('package_name', models.CharField(max_length=100, unique=True)),
                ('package_features1', models.TextField(blank=True, null=True)),
                ('package_features2', models.TextField(blank=True, null=True)),
                ('package_features3', models.TextField(blank=True, null=True)),
                ('package_features4', models.TextField(blank=True, null=True)),
                ('package_features5', models.TextField(blank=True, null=True)),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEPRECATED', 'Deprecated')], default='ACTIVE', max_length=20)),
                ('package_deliverable1', models.TextField(blank=True, null=True)),
                ('package_deliverable2', models.TextField(blank=True, null=True)),
                ('package_deliverable3', models.TextField(blank=True, null=True)),
                ('package_deliverable4', models.TextField(blank=True, null=True)),
                ('package_deliverable5', models.TextField(blank=True, null=True)),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='assessments.assessmentversion')),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['package_name'],
                'indexes': [models.Index(fields=['public_id'], name='packages_public__e493f4_idx'), models.Index(fields=['assessment_version'], name='packages_assessm_be38e0_idx'), models.Index(fields=['package_name'], name='packages_package_754928_idx'), models.Index(fields=['status'], name='packages_status_3149ce_idx')],
            },
        ),
    ]
