# Generated by Django 6.0.7 on 2026-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_package_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('COACHING_INSTITUTE', 'Coaching Institute'), ('COUNSELLOR', 'Independent Counsellor'), ('ENTERPRISE', 'Enterprise'), ('NGO', 'NGO'), ('FRANCHISE', 'Franchise'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
    ]
