# Generated by Django 6.0.7 on 2026-09-18 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('member_type', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('COUNSELLOR', 'Counsellor'), ('TEACHER', 'Teacher'), ('COORDINATOR', 'Coordinator'), ('STAFF', 'Staff')], max_length=40)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed')], default='INVITED', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organization_members',
            },
        ),
        migrations.AlterModelOptions(
            name='registrationlink',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='registrationlink',
            name='registratio_campaig_80a58c_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrationlink',
            name='registratio_link_co_2c8477_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrationlink',
            name='registratio_is_acti_9bd6cc_idx',
        ),
        migrations.AddField(
            model_name='registrationlink',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registration_links', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationlink',
            name='public_slug',
            field=models.CharField(db_index=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationlink',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='registrationlink',
            name='token_hash',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='registrationlink',
            index=models.Index(fields=['organization'], name='registratio_organiz_98cc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationlink',
            index=models.Index(fields=['public_slug'], name='registratio_public__e5eea8_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationlink',
            index=models.Index(fields=['status'], name='registratio_status_901a35_idx'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='registrationlink',
            name='allow_duplicate_email',
        ),
        migrations.RemoveField(
            model_name='registrationlink',
            name='allow_duplicate_mobile',
        ),
        migrations.RemoveField(
            model_name='registrationlink',
            name='assessment_version',
        ),
        migrations.RemoveField(
            model_name='registrationlink',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='registrationlink',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registrationlink',
            name='link_code',
        ),
        migrations.RemoveField(
            model_name='registrationlink',
            name='registration_channel',
        ),
        migrations.RemoveField(
            model_name='registrationlink',
            name='registration_source',
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['public_id'], name='organizatio_public__4fa044_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization'], name='organizatio_organiz_a66366_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user'], name='organizatio_user_id_1a6a95_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['member_type'], name='organizatio_member__5427d0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['status'], name='organizatio_status_e263a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_user'),
        ),
    ]
