# Generated by Django 6.0.7 on 2026-09-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organizationpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationlink',
            old_name='display_name',
            new_name='link_name',
        ),
        migrations.RenameField(
            model_name='registrationlink',
            old_name='registrations_count',
            new_name='registration_count',
        ),
    ]
