# Generated by Django 6.0.7 on 2026-09-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_rename_display_name_registrationlink_link_name_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE "organization_members" (
                    "id" bigint NOT NULL PRIMARY KEY
                        GENERATED BY DEFAULT AS IDENTITY,

                    "public_id" uuid NOT NULL UNIQUE,

                    "member_type" varchar(40) NOT NULL,

                    "status" varchar(20) NOT NULL
                        DEFAULT 'INVITED',

                    "joined_at" timestamp with time zone NULL,

                    "created_at" timestamp with time zone NOT NULL,

                    "updated_at" timestamp with time zone NOT NULL,

                    "invited_by_id" bigint NULL
                        REFERENCES "users"("id")
                        DEFERRABLE INITIALLY DEFERRED,

                    "organization_id" bigint NOT NULL
                        REFERENCES "organizations"("id")
                        DEFERRABLE INITIALLY DEFERRED,

                    "user_id" bigint NOT NULL
                        REFERENCES "users"("id")
                        DEFERRABLE INITIALLY DEFERRED,

                    CONSTRAINT "unique_organization_user"
                        UNIQUE ("organization_id", "user_id")
                );

                CREATE INDEX "organizatio_public__4fa044_idx"
                    ON "organization_members" ("public_id");

                CREATE INDEX "organizatio_organiz_a66366_idx"
                    ON "organization_members" ("organization_id");

                CREATE INDEX "organizatio_user_id_1a6a95_idx"
                    ON "organization_members" ("user_id");

                CREATE INDEX "organizatio_member__5427d0_idx"
                    ON "organization_members" ("member_type");

                CREATE INDEX "organizatio_status_e263a2_idx"
                    ON "organization_members" ("status");

                CREATE INDEX "organization_members_invited_by_id_b9fd2c81"
                    ON "organization_members" ("invited_by_id");

                CREATE INDEX "organization_members_organization_id_d55f4961"
                    ON "organization_members" ("organization_id");

                CREATE INDEX "organization_members_user_id_e6013fda"
                    ON "organization_members" ("user_id");
            """,

            reverse_sql="""
                DROP TABLE IF EXISTS "organization_members";
            """,
        ),
    ]