# Generated by Django 6.0.7 on 2026-09-22 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_recreate_organization_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpackage',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='organizationpackage',
            name='negotiated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='organizationpackage',
            name='seat_limit',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
