# Generated by Django 6.0.7 on 2026-09-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0044_alter_interpretationrule_title'),
        ('organizations', '0011_alter_organizationpackage_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='assessments.grade'),
        ),
        migrations.AlterField(
            model_name='package',
            name='assessment_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='assessments.assessmentversion'),
        ),
    ]
