# Generated by Django 6.0.7 on 2026-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_package_grade_alter_package_assessment_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
