# Generated by Django 6.0.7 on 2026-09-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_public_id'),
        ('students', '0003_alter_studentregistration_assigned_counsellor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organizationmember',
            name='organizatio_organiz_a66366_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationmember',
            name='organizatio_user_id_1a6a95_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationmember',
            name='organizatio_status_e263a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationmember',
            name='organizatio_employe_626a8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationmember',
            name='organizatio_is_prim_9be4b6_idx',
        ),
        migrations.RemoveConstraint(
            model_name='organizationmember',
            name='unique_organization_user',
        ),
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
    ]
