# Generated by Django 6.0.7 on 2026-09-23 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_organizationmember_organizatio_organiz_a66366_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verification_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='email_verif_user_id_df8513_idx'), models.Index(fields=['otp'], name='email_verif_otp_e34e09_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_4f1a01_idx'), models.Index(fields=['is_verified'], name='email_verif_is_veri_fb6b72_idx')],
            },
        ),
    ]
