# Generated by Django 6.0.7 on 2026-07-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluation', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(editable=False, unique=True)),
                ('template_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('CAREER_V1', 'Career Report V1'), ('CAREER_V2', 'Career Report V2'), ('CAREER_V3', 'Career Report V3'), ('PERSONALITY', 'Personality'), ('PSYCHOMETRIC', 'Psychometric'), ('ENTERPRISE', 'Enterprise'), ('COUNSELLOR', 'Counsellor')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_config_json', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(editable=False, unique=True)),
                ('report_version', models.CharField(max_length=20)),
                ('report_title', models.CharField(max_length=255)),
                ('report_json', models.JSONField()),
                ('report_metadata_json', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField()),
                ('generated_by', models.CharField(blank=True, help_text='Evaluation Engine / AI Engine / Manual', max_length=50, null=True)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='GENERATING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_instance', to='evaluation.evaluationresult')),
                ('student_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_instances', to='students.studentregistration')),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_instances', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Instance',
                'verbose_name_plural': 'Report Instances',
                'db_table': 'report_instances',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(editable=False, unique=True)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('DOCX', 'DOCX')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('storage_provider', models.CharField(choices=[('LOCAL', 'Local'), ('AWS_S3', 'AWS S3'), ('AZURE', 'Azure'), ('GCS', 'Google Cloud Storage')], default='AWS_S3', max_length=20)),
                ('download_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='reports.reportinstance')),
            ],
            options={
                'db_table': 'report_files',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_instance'], name='report_file_report__035285_idx'), models.Index(fields=['file_type'], name='report_file_file_ty_0ca621_idx'), models.Index(fields=['storage_provider'], name='report_file_storage_b608ef_idx'), models.Index(fields=['generated_at'], name='report_file_generat_897f61_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['template_code'], name='report_temp_templat_3f23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['report_type'], name='report_temp_report__568538_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['status'], name='report_temp_status_dbfc36_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['language'], name='report_temp_languag_b32b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['report_template'], name='report_inst_report__55bf7c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['evaluation_result'], name='report_inst_evaluat_4c5d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['student_registration'], name='report_inst_student_00707f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['status'], name='report_inst_status_1cb74a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['generated_at'], name='report_inst_generat_56a6bb_idx'),
        ),
    ]
