# Generated by Django 6.0.7 on 2026-07-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('allowed_attempts', models.PositiveIntegerField(default=1)),
                ('attempts_used', models.PositiveIntegerField(default=0)),
                ('assignment_status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('STARTED', 'Started'), ('SUBMITTED', 'Submitted'), ('EVALUATED', 'Evaluted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_assignments', to='assessments.assessmentversion')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL)),
                ('student_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assignments', to='students.studentregistration')),
            ],
            options={
                'verbose_name': 'Assessment Assignment',
                'verbose_name_plural': 'Assessment Assignments',
                'db_table': 'assessment_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_taken_seconds', models.PositiveIntegerField(blank=True, help_text='Total duration in seconds', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, help_text='Desktop, Mobile, Tablet', max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('attempt_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted'), ('EVALUATED', 'Evaluated')], default='NOT_STARTED', max_length=20)),
                ('assessment_snapshot_json', models.JSONField(blank=True, help_text='Stores assessment configuration snapshot at the time of attempt.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='runtime.assessmentassignment')),
            ],
            options={
                'verbose_name': 'Assessment Attempt',
                'verbose_name_plural': 'Assessment Attempts',
                'db_table': 'assessment_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('selected_response_json', models.JSONField(help_text="Stores student's answer in JSON format")),
                ('is_skipped', models.BooleanField(default=False)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='runtime.assessmentattempt')),
                ('assessment_blueprint_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmentblueprintitem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.question')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'db_table': 'student_responses',
                'ordering': ['assessment_attempt', 'assessment_blueprint_item'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['public_id'], name='assessment__public__273ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['student_registration'], name='assessment__student_a673b8_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['assessment_version'], name='assessment__assessm_997baa_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['assignment_status'], name='assessment__assignm_65c342_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['assigned_at'], name='assessment__assigne_a867dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentassignment',
            constraint=models.UniqueConstraint(fields=('student_registration', 'assessment_version'), name='unique_student_assessment_assignment'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['assessment_assignment'], name='assessment__assessm_8cde2d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['attempt_status'], name='assessment__attempt_1d3e90_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['started_at'], name='assessment__started_9e9f51_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['submitted_at'], name='assessment__submitt_312fab_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['last_activity_at'], name='assessment__last_ac_cb2b88_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('assessment_assignment', 'attempt_number'), name='unique_attempt_number_per_assignment'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['public_id'], name='student_res_public__eebad8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['assessment_attempt'], name='student_res_assessm_983320_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['assessment_blueprint_item'], name='student_res_assessm_71ef4c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['question'], name='student_res_questio_bda326_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['is_skipped'], name='student_res_is_skip_d91903_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['is_marked_for_review'], name='student_res_is_mark_178703_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['answered_at'], name='student_res_answere_ee3bef_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentresponse',
            constraint=models.UniqueConstraint(fields=('assessment_attempt', 'assessment_blueprint_item'), name='unique_response_per_question_attempt'),
        ),
    ]
